layout_spectrum: 0.8153457
typography_spectrum: 0.3878584
color:
  lightness: 0.8786923
  brandStrength: 0.3988155
  saturation: 0.8794267
  rhythmicContrast: 0.7310287
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Joe Hartley
